
sudo: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - ~/.npm
notifications:
  email: false
install: npm install
script:
- npm run cover
- npm run build
branches:
  only: master